# Generated by Django 6.0.5 on 2026-05-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('id', 'category', 'period')},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
