# Generated by Django 6.0.5 on 2026-05-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_formula', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price_formula', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price_formula', models.TextField(blank=True, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level_formula', models.TextField(blank=True, null=True)),
                ('is_low_stock', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='records.category')),
            ],
        ),
    ]
